spring: 
    profiles: 
        active: 
            - dev: 
---

spring: 
    profiles: dev
        application: 
              name: microservicecloud-config-yang-dev
    
---

spring: 
    profiles: test
        application: 
              name: microservicecloud-config-yang-test         